# Tauri设备信号网关配置文件 - 本地开发版本
# 这是用于本地开发的配置，假设所有服务都在localhost运行

[server]
host = "127.0.0.1"
port = 8080

# MariaDB 10.4 配置
[mariadb]
host = "localhost"
port = 3306
database = "device_data"
username = "root"
password = ""  # 本地开发通常root用户无密码

# InfluxDB 1.8 配置
[influxdb]
url = "http://localhost:8086"
database = "device_signals"

# Kafka 0.9.0.0 配置
[kafka]
brokers = "localhost:9092"
topic = "device-signals"
client_id = "tauri-device-gateway"